RENDER_PRESETS = {
    'PREVIEW': {
        'engine': 'BLENDER_EEVEE_NEXT',
        'resolution_x': 1280,
        'resolution_y': 720,
        'samples': 32,
        'use_denoise': False,
        'film_transparent': False,
        'file_format': 'PNG',
        'color_depth': '8',
        'color_mode': 'RGB',
        'color_management': 'Filmic',
    },
    'PRODUCT': {
        'engine': 'CYCLES',
        'resolution_x': 1920,
        'resolution_y': 1080,
        'samples': 256,
        'use_denoise': True,
        'film_transparent': True,
        'file_format': 'PNG',
        'color_depth': '16',
        'color_mode': 'RGBA',
        'color_management': 'Filmic',
    },
    'BATCH': {
        'engine': 'BLENDER_EEVEE_NEXT',
        'resolution_x': 1920,
        'resolution_y': 1080,
        'samples': 64,
        'use_denoise': False,
        'film_transparent': True,
        'file_format': 'PNG',
        'color_depth': '16',
        'color_mode': 'RGBA',
        'color_management': 'Filmic',
    },
    'DIGITAL_TWIN': {
        'engine': 'BLENDER_EEVEE_NEXT',
        'resolution_x': 1280,
        'resolution_y': 720,
        'samples': 16,
        'use_denoise': False,
        'film_transparent': False,
        'file_format': 'PNG',
        'color_depth': '8',
        'color_mode': 'RGB',
        'color_management': 'Standard',
    },
}
